### ISSUE TITLE
Discord Nitro limiting contexts that can be viewed

### ISSUE THREAD

**Issue by vintrocode** [plastic-labs/tutor-gpt#10]
Sometimes, someone with Nitro will set a long context (> 2k chars). Then, I think because the bot doesn't have nitro, it can't respond with a message greater than that threshold. So whenever you use the `/context` command with no text in order to see the context that was set by someone else, the application can't respond. Traceback:
```
File "/usr/local/lib/python3.10/site-packages/discord/commands/core.py", line 132, in wrapped
raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.content: Must be 2000 or fewer in length.
```

**Comment by VVoruganti** [comment]
No longer using `/context` or a similar parallel. Should be ok to stick too the context window of discord for now
