### ISSUE TITLE
Improve Parsing of Generated Text

### ISSUE THREAD

**Issue by vintrocode** [plastic-labs/tutor-gpt#25]
We need to remove the dependency on the model following our pattern perfectly for parsing out the thoughts and responses
- it can misspell the following word (like we saw it spell "Studen:" [once](https://discord.com/channels/1016845111637839922/1073429619639853066/1080233497073025065)) 
- it can mis-interpret the pattern, thinking it's Thought-Student [only](https://discord.com/channels/1076192451997474938/1088994552070803568/1091401960189595688)

Some quick chatting with ChatGPT got me the following string that parses everything between "Thought:" and the first newline character:
```
import re
...
result = re.findall(r'Thought: (.*?)(?=\n|$)', string, re.DOTALL)[-1].strip()
```

This pattern should be applicable across the board. Can't depend on it following the pattern or generating the correct next term.

**Comment by hyusap** [comment]
should be resolved with the implementation of chat history?
