### ISSUE TITLE
Inconsistent List Formatting

### ISSUE THREAD

**Issue by VVoruganti** [plastic-labs/tutor-gpt#56]
When Bloom/tutor-gpt is making lists occasionally it will format different entries differently. A few examples were raised by a user in the discord server. 

![](https://cdn.discordapp.com/attachments/1092832809204322415/1139640495602159796/image0.jpg)
entry 10  ^

And the below instance on the streamlit shows it changing on both 9 & 10

![](https://cdn.discordapp.com/attachments/1092832809204322415/1139613597878734928/image0.jpg)

**Comment by hyusap** [comment]
does this still happen? couldn't reproduce on discord or web. could have been solved with newer models.

**Comment by VVoruganti** [comment]
Closing as stale - hard to reproduce and hasn't been reported in quite a while
