### ISSUE TITLE
Add exception for when the bot's ID number comes up

### ISSUE THREAD

**Issue by vintrocode** [plastic-labs/tutor-gpt#61]
When it sees its ID number in a message it replies. I believe this is because Discord parses "@Bloom" on the backend as "@1098230..."

<img width="1074" alt="image" src="https://github.com/plastic-labs/tutor-gpt/assets/77507980/8e83f25c-3f1d-4692-8435-90dffb63c766">

**Comment by hyusap** [comment]
seems to have been resolved already

<img width="726" alt="Screenshot 2023-12-11 at 6 58 12 PM" src="https://github.com/plastic-labs/tutor-gpt/assets/61765149/a938c5b2-5aff-44eb-91a4-d9efdee0d951">
